# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.3.0
      with:
        # A list of all paths to test
        python-root-list: '.'
        # Use Pylint
        use-pylint:  true
        # Use pycodestyle
        use-pycodestyle:  true
        # Use Flake8
        use-flake8:  true
        # Use Black
        use-black: true
        # Use mypy
        use-mypy:  true
        # Use isort
        use-isort:  true
        # Extra options: pylint $(extra-pylint-options) $(python-root-list)
        extra-pylint-options: ''
        # Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)
        extra-pycodestyle-options: ''
      # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
        extra-flake8-options: ''
      # Extra options: black --check $(extra-black-options) $(python-root-list)
        extra-black-options: ''
      # Extra options: mypy $(extra-mypy-options) $(python-root-list)
        extra-mypy-options: ''
      # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff 
        extra-isort-options: ''
 
