# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: COLOUR_Outfit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint .
        ...

    - name: Lint with black
      run: |
        pip install black
        black .
        ...

    - name: Lint with isort
      run: |
        pip install isort
        isort .
        ...

    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle .
        ...

    - name: Lint with mypy
      run: |
        pip install mypy
        mypy .
        ...
          
    - name: commit isort changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
    - name: push isort changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

